/*
BWDK API

Testing SellerProfileManagementAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package bwdk_sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_bwdk_sdk_SellerProfileManagementAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SellerProfileManagementAPIService MerchantApiV1AuthStatusRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SellerProfileManagementAPI.MerchantApiV1AuthStatusRetrieve(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
