/*
BWDK API

Testing DefaultApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package bwdk_sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_bwdk_sdk_DefaultApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefaultApiService MerchantApiV1AuthStatusRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DefaultApi.MerchantApiV1AuthStatusRetrieve(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultApiService OrderApiV1CreateOrderCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DefaultApi.OrderApiV1CreateOrderCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultApiService OrderApiV1ManagerCancelShipmentCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orderUuid string

		resp, httpRes, err := apiClient.DefaultApi.OrderApiV1ManagerCancelShipmentCreate(context.Background(), orderUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultApiService OrderApiV1ManagerChangeShippingMethodUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orderUuid string

		resp, httpRes, err := apiClient.DefaultApi.OrderApiV1ManagerChangeShippingMethodUpdate(context.Background(), orderUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultApiService OrderApiV1ManagerList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DefaultApi.OrderApiV1ManagerList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultApiService OrderApiV1ManagerPaidList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DefaultApi.OrderApiV1ManagerPaidList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultApiService OrderApiV1ManagerRefundCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orderUuid string

		resp, httpRes, err := apiClient.DefaultApi.OrderApiV1ManagerRefundCreate(context.Background(), orderUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultApiService OrderApiV1ManagerRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orderUuid string

		resp, httpRes, err := apiClient.DefaultApi.OrderApiV1ManagerRetrieve(context.Background(), orderUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultApiService OrderApiV1ManagerReviveShipmentCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orderUuid string

		resp, httpRes, err := apiClient.DefaultApi.OrderApiV1ManagerReviveShipmentCreate(context.Background(), orderUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultApiService OrderApiV1ManagerUpdateStatusUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orderUuid string

		resp, httpRes, err := apiClient.DefaultApi.OrderApiV1ManagerUpdateStatusUpdate(context.Background(), orderUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultApiService OrderApiV1ManagerVerifyCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orderUuid string

		resp, httpRes, err := apiClient.DefaultApi.OrderApiV1ManagerVerifyCreate(context.Background(), orderUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultApiService WalletsApiV1WalletBalanceRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DefaultApi.WalletsApiV1WalletBalanceRetrieve(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
