/*
BWDK API

Testing MerchantOrdersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package bwdk_sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_bwdk_sdk_MerchantOrdersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MerchantOrdersAPIService OrderApiV1CreateOrderCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MerchantOrdersAPI.OrderApiV1CreateOrderCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MerchantOrdersAPIService OrderApiV1ManagerList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MerchantOrdersAPI.OrderApiV1ManagerList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MerchantOrdersAPIService OrderApiV1ManagerPaidList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MerchantOrdersAPI.OrderApiV1ManagerPaidList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MerchantOrdersAPIService OrderApiV1ManagerRefundCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orderUuid string

		resp, httpRes, err := apiClient.MerchantOrdersAPI.OrderApiV1ManagerRefundCreate(context.Background(), orderUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MerchantOrdersAPIService OrderApiV1ManagerRetrieve", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orderUuid string

		resp, httpRes, err := apiClient.MerchantOrdersAPI.OrderApiV1ManagerRetrieve(context.Background(), orderUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MerchantOrdersAPIService OrderApiV1ManagerUpdateStatusUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orderUuid string

		resp, httpRes, err := apiClient.MerchantOrdersAPI.OrderApiV1ManagerUpdateStatusUpdate(context.Background(), orderUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MerchantOrdersAPIService OrderApiV1ManagerVerifyCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orderUuid string

		resp, httpRes, err := apiClient.MerchantOrdersAPI.OrderApiV1ManagerVerifyCreate(context.Background(), orderUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
