/*
BWDK API

Testing OrderShippingAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package bwdk_sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_bwdk_sdk_OrderShippingAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OrderShippingAPIService OrderApiV1ManagerCancelShipmentCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orderUuid string

		resp, httpRes, err := apiClient.OrderShippingAPI.OrderApiV1ManagerCancelShipmentCreate(context.Background(), orderUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrderShippingAPIService OrderApiV1ManagerChangeShippingMethodUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orderUuid string

		resp, httpRes, err := apiClient.OrderShippingAPI.OrderApiV1ManagerChangeShippingMethodUpdate(context.Background(), orderUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrderShippingAPIService OrderApiV1ManagerReviveShipmentCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orderUuid string

		resp, httpRes, err := apiClient.OrderShippingAPI.OrderApiV1ManagerReviveShipmentCreate(context.Background(), orderUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
