/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// OrderShippingAPIService OrderShippingAPI service
type OrderShippingAPIService service

type ApiOrderApiV1ManagerCancelShipmentCreateRequest struct {
	ctx context.Context
	ApiService *OrderShippingAPIService
	orderUuid string
}

func (r ApiOrderApiV1ManagerCancelShipmentCreateRequest) Execute() (*MerchantOrderCancelShipmentResponse, *http.Response, error) {
	return r.ApiService.OrderApiV1ManagerCancelShipmentCreateExecute(r)
}

/*
OrderApiV1ManagerCancelShipmentCreate Cancel Shipment

<div dir="rtl" style="text-align: right;">

لغو مرسوله دیجی‌اکسپرس

## توضیحات

این endpoint برای لغو یک مرسوله ثبت‌شده در سرویس دیجی‌اکسپرس استفاده می‌شود. پس از لغو موفق، مرسوله از صف ارسال خارج می‌شود.

نیاز به **API_KEY** فروشنده دارد.

## شرایط لغو

* سفارش باید دارای روش ارسال **DigiExpress** باشد
* مرسوله باید در وضعیت **در انتظار تحویل به پیک** (Request for Pickup) باشد

</div>

```mermaid
sequenceDiagram
    participant M as فروشنده
    participant API as BWDK API
    participant DX as دیجی‌اکسپرس

    M->>API: POST /order/api/v1/manager/{order_uuid}/cancel-shipment/
    Note over M,API: Header: X-API-KEY (بدون بدنه)

    alt روش ارسال DigiExpress نیست
        API-->>M: 400 خطا
        Note over API,M: {error: "Selected shipping method is not DigiExpress"}
    else مرسوله قابل لغو نیست
        API-->>M: 400 خطا
        Note over API,M: {error: "..."}
    else لغو موفق
        API->>DX: لغو مرسوله
        DX-->>API: تأیید لغو
        API-->>M: 200 موفق
        Note over API,M: {message, order_uuid, status, status_display}
    end
```


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param orderUuid
 @return ApiOrderApiV1ManagerCancelShipmentCreateRequest
*/
func (a *OrderShippingAPIService) OrderApiV1ManagerCancelShipmentCreate(ctx context.Context, orderUuid string) ApiOrderApiV1ManagerCancelShipmentCreateRequest {
	return ApiOrderApiV1ManagerCancelShipmentCreateRequest{
		ApiService: a,
		ctx: ctx,
		orderUuid: orderUuid,
	}
}

// Execute executes the request
//  @return MerchantOrderCancelShipmentResponse
func (a *OrderShippingAPIService) OrderApiV1ManagerCancelShipmentCreateExecute(r ApiOrderApiV1ManagerCancelShipmentCreateRequest) (*MerchantOrderCancelShipmentResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *MerchantOrderCancelShipmentResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OrderShippingAPIService.OrderApiV1ManagerCancelShipmentCreate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/order/api/v1/manager/{order_uuid}/cancel-shipment/"
	localVarPath = strings.Replace(localVarPath, "{"+"order_uuid"+"}", url.PathEscape(parameterValueToString(r.orderUuid, "orderUuid")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["MerchantAPIKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v OrderError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v OrderError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiOrderApiV1ManagerChangeShippingMethodUpdateRequest struct {
	ctx context.Context
	ApiService *OrderShippingAPIService
	orderUuid string
	orderDetail *OrderDetail
}

func (r ApiOrderApiV1ManagerChangeShippingMethodUpdateRequest) OrderDetail(orderDetail OrderDetail) ApiOrderApiV1ManagerChangeShippingMethodUpdateRequest {
	r.orderDetail = &orderDetail
	return r
}

func (r ApiOrderApiV1ManagerChangeShippingMethodUpdateRequest) Execute() (*OrderDetail, *http.Response, error) {
	return r.ApiService.OrderApiV1ManagerChangeShippingMethodUpdateExecute(r)
}

/*
OrderApiV1ManagerChangeShippingMethodUpdate Change Shipping Method

<div dir="rtl" style="text-align: right;">

تغییر روش ارسال سفارش

## توضیحات

این endpoint به فروشنده اجازه می‌دهد روش ارسال یک سفارش را تغییر دهد. این عملیات معمولاً زمانی استفاده می‌شود که فروشنده بخواهد از DigiExpress به روش ارسال پیش‌فرض (یا بالعکس) تغییر دهد.

نیاز به **API_KEY** فروشنده دارد.

## پارامترهای ورودی

* **updated_shipping**: شناسه روش ارسال جدید
* **preparation_time** (اختیاری): زمان آماده‌سازی (روز) برای DigiExpress

</div>


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param orderUuid
 @return ApiOrderApiV1ManagerChangeShippingMethodUpdateRequest
*/
func (a *OrderShippingAPIService) OrderApiV1ManagerChangeShippingMethodUpdate(ctx context.Context, orderUuid string) ApiOrderApiV1ManagerChangeShippingMethodUpdateRequest {
	return ApiOrderApiV1ManagerChangeShippingMethodUpdateRequest{
		ApiService: a,
		ctx: ctx,
		orderUuid: orderUuid,
	}
}

// Execute executes the request
//  @return OrderDetail
func (a *OrderShippingAPIService) OrderApiV1ManagerChangeShippingMethodUpdateExecute(r ApiOrderApiV1ManagerChangeShippingMethodUpdateRequest) (*OrderDetail, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OrderDetail
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OrderShippingAPIService.OrderApiV1ManagerChangeShippingMethodUpdate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/order/api/v1/manager/{order_uuid}/change-shipping-method/"
	localVarPath = strings.Replace(localVarPath, "{"+"order_uuid"+"}", url.PathEscape(parameterValueToString(r.orderUuid, "orderUuid")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.orderDetail == nil {
		return localVarReturnValue, nil, reportError("orderDetail is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/x-www-form-urlencoded", "multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.orderDetail
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["MerchantAPIKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiOrderApiV1ManagerReviveShipmentCreateRequest struct {
	ctx context.Context
	ApiService *OrderShippingAPIService
	orderUuid string
	reviveShipment *ReviveShipment
}

func (r ApiOrderApiV1ManagerReviveShipmentCreateRequest) ReviveShipment(reviveShipment ReviveShipment) ApiOrderApiV1ManagerReviveShipmentCreateRequest {
	r.reviveShipment = &reviveShipment
	return r
}

func (r ApiOrderApiV1ManagerReviveShipmentCreateRequest) Execute() (*MerchantOrderReviveShipmentResponse, *http.Response, error) {
	return r.ApiService.OrderApiV1ManagerReviveShipmentCreateExecute(r)
}

/*
OrderApiV1ManagerReviveShipmentCreate Revive Shipment

<div dir="rtl" style="text-align: right;">

احیای مرسوله دیجی‌اکسپرس

## توضیحات

این endpoint برای احیای (reactivate) یک مرسوله دیجی‌اکسپرس که قبلاً لغو شده یا در وضعیت غیرفعال است استفاده می‌شود. با ارسال `preparation_time` (زمان آماده‌سازی بر حسب روز)، زمان جدید آماده بودن بار تنظیم می‌شود.

نیاز به **API_KEY** فروشنده دارد.

## پارامترهای ورودی

* **preparation_time** (اختیاری، پیش‌فرض: ۲): تعداد روز تا آماده‌شدن بار برای تحویل به پیک

## شرایط

* سفارش باید دارای روش ارسال **DigiExpress** باشد
* مرسوله باید در وضعیت قابل احیا باشد

</div>

```mermaid
sequenceDiagram
    participant M as فروشنده
    participant API as BWDK API
    participant DX as دیجی‌اکسپرس

    M->>API: POST /order/api/v1/manager/{order_uuid}/revive-shipment/
    Note over M,API: Header: X-API-KEY<br/>{preparation_time: 2}

    alt روش ارسال DigiExpress نیست
        API-->>M: 400 خطا
        Note over API,M: {error: "Selected shipping method is not DigiExpress"}
    else احیا موفق
        API->>DX: احیای مرسوله با زمان جدید
        DX-->>API: تأیید احیا
        API-->>M: 200 موفق
        Note over API,M: {message, order_uuid, status, status_display}
    end
```


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param orderUuid
 @return ApiOrderApiV1ManagerReviveShipmentCreateRequest
*/
func (a *OrderShippingAPIService) OrderApiV1ManagerReviveShipmentCreate(ctx context.Context, orderUuid string) ApiOrderApiV1ManagerReviveShipmentCreateRequest {
	return ApiOrderApiV1ManagerReviveShipmentCreateRequest{
		ApiService: a,
		ctx: ctx,
		orderUuid: orderUuid,
	}
}

// Execute executes the request
//  @return MerchantOrderReviveShipmentResponse
func (a *OrderShippingAPIService) OrderApiV1ManagerReviveShipmentCreateExecute(r ApiOrderApiV1ManagerReviveShipmentCreateRequest) (*MerchantOrderReviveShipmentResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *MerchantOrderReviveShipmentResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OrderShippingAPIService.OrderApiV1ManagerReviveShipmentCreate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/order/api/v1/manager/{order_uuid}/revive-shipment/"
	localVarPath = strings.Replace(localVarPath, "{"+"order_uuid"+"}", url.PathEscape(parameterValueToString(r.orderUuid, "orderUuid")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/x-www-form-urlencoded", "multipart/form-data"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.reviveShipment
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["MerchantAPIKeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v OrderError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v OrderError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
