/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
)

// checks if the ReviveShipment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReviveShipment{}

// ReviveShipment struct for ReviveShipment
type ReviveShipment struct {
	// The preparation time for the order in days.
	PreparationTime NullableInt32 `json:"preparation_time,omitempty"`
}

// NewReviveShipment instantiates a new ReviveShipment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReviveShipment() *ReviveShipment {
	this := ReviveShipment{}
	return &this
}

// NewReviveShipmentWithDefaults instantiates a new ReviveShipment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReviveShipmentWithDefaults() *ReviveShipment {
	this := ReviveShipment{}
	return &this
}

// GetPreparationTime returns the PreparationTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReviveShipment) GetPreparationTime() int32 {
	if o == nil || IsNil(o.PreparationTime.Get()) {
		var ret int32
		return ret
	}
	return *o.PreparationTime.Get()
}

// GetPreparationTimeOk returns a tuple with the PreparationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReviveShipment) GetPreparationTimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PreparationTime.Get(), o.PreparationTime.IsSet()
}

// HasPreparationTime returns a boolean if a field has been set.
func (o *ReviveShipment) HasPreparationTime() bool {
	if o != nil && o.PreparationTime.IsSet() {
		return true
	}

	return false
}

// SetPreparationTime gets a reference to the given NullableInt32 and assigns it to the PreparationTime field.
func (o *ReviveShipment) SetPreparationTime(v int32) {
	o.PreparationTime.Set(&v)
}
// SetPreparationTimeNil sets the value for PreparationTime to be an explicit nil
func (o *ReviveShipment) SetPreparationTimeNil() {
	o.PreparationTime.Set(nil)
}

// UnsetPreparationTime ensures that no value is present for PreparationTime, not even an explicit nil
func (o *ReviveShipment) UnsetPreparationTime() {
	o.PreparationTime.Unset()
}

func (o ReviveShipment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReviveShipment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.PreparationTime.IsSet() {
		toSerialize["preparation_time"] = o.PreparationTime.Get()
	}
	return toSerialize, nil
}

type NullableReviveShipment struct {
	value *ReviveShipment
	isSet bool
}

func (v NullableReviveShipment) Get() *ReviveShipment {
	return v.value
}

func (v *NullableReviveShipment) Set(val *ReviveShipment) {
	v.value = val
	v.isSet = true
}

func (v NullableReviveShipment) IsSet() bool {
	return v.isSet
}

func (v *NullableReviveShipment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReviveShipment(val *ReviveShipment) *NullableReviveShipment {
	return &NullableReviveShipment{value: val, isSet: true}
}

func (v NullableReviveShipment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReviveShipment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


