/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaginatedMerchantPaidOrderListList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedMerchantPaidOrderListList{}

// PaginatedMerchantPaidOrderListList struct for PaginatedMerchantPaidOrderListList
type PaginatedMerchantPaidOrderListList struct {
	Next NullableString `json:"next,omitempty"`
	Previous NullableString `json:"previous,omitempty"`
	Results []MerchantPaidOrderList `json:"results"`
}

type _PaginatedMerchantPaidOrderListList PaginatedMerchantPaidOrderListList

// NewPaginatedMerchantPaidOrderListList instantiates a new PaginatedMerchantPaidOrderListList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedMerchantPaidOrderListList(results []MerchantPaidOrderList) *PaginatedMerchantPaidOrderListList {
	this := PaginatedMerchantPaidOrderListList{}
	this.Results = results
	return &this
}

// NewPaginatedMerchantPaidOrderListListWithDefaults instantiates a new PaginatedMerchantPaidOrderListList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedMerchantPaidOrderListListWithDefaults() *PaginatedMerchantPaidOrderListList {
	this := PaginatedMerchantPaidOrderListList{}
	return &this
}

// GetNext returns the Next field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedMerchantPaidOrderListList) GetNext() string {
	if o == nil || IsNil(o.Next.Get()) {
		var ret string
		return ret
	}
	return *o.Next.Get()
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedMerchantPaidOrderListList) GetNextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Next.Get(), o.Next.IsSet()
}

// HasNext returns a boolean if a field has been set.
func (o *PaginatedMerchantPaidOrderListList) HasNext() bool {
	if o != nil && o.Next.IsSet() {
		return true
	}

	return false
}

// SetNext gets a reference to the given NullableString and assigns it to the Next field.
func (o *PaginatedMerchantPaidOrderListList) SetNext(v string) {
	o.Next.Set(&v)
}
// SetNextNil sets the value for Next to be an explicit nil
func (o *PaginatedMerchantPaidOrderListList) SetNextNil() {
	o.Next.Set(nil)
}

// UnsetNext ensures that no value is present for Next, not even an explicit nil
func (o *PaginatedMerchantPaidOrderListList) UnsetNext() {
	o.Next.Unset()
}

// GetPrevious returns the Previous field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PaginatedMerchantPaidOrderListList) GetPrevious() string {
	if o == nil || IsNil(o.Previous.Get()) {
		var ret string
		return ret
	}
	return *o.Previous.Get()
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedMerchantPaidOrderListList) GetPreviousOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Previous.Get(), o.Previous.IsSet()
}

// HasPrevious returns a boolean if a field has been set.
func (o *PaginatedMerchantPaidOrderListList) HasPrevious() bool {
	if o != nil && o.Previous.IsSet() {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given NullableString and assigns it to the Previous field.
func (o *PaginatedMerchantPaidOrderListList) SetPrevious(v string) {
	o.Previous.Set(&v)
}
// SetPreviousNil sets the value for Previous to be an explicit nil
func (o *PaginatedMerchantPaidOrderListList) SetPreviousNil() {
	o.Previous.Set(nil)
}

// UnsetPrevious ensures that no value is present for Previous, not even an explicit nil
func (o *PaginatedMerchantPaidOrderListList) UnsetPrevious() {
	o.Previous.Unset()
}

// GetResults returns the Results field value
func (o *PaginatedMerchantPaidOrderListList) GetResults() []MerchantPaidOrderList {
	if o == nil {
		var ret []MerchantPaidOrderList
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedMerchantPaidOrderListList) GetResultsOk() ([]MerchantPaidOrderList, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedMerchantPaidOrderListList) SetResults(v []MerchantPaidOrderList) {
	o.Results = v
}

func (o PaginatedMerchantPaidOrderListList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedMerchantPaidOrderListList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Next.IsSet() {
		toSerialize["next"] = o.Next.Get()
	}
	if o.Previous.IsSet() {
		toSerialize["previous"] = o.Previous.Get()
	}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *PaginatedMerchantPaidOrderListList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedMerchantPaidOrderListList := _PaginatedMerchantPaidOrderListList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedMerchantPaidOrderListList)

	if err != nil {
		return err
	}

	*o = PaginatedMerchantPaidOrderListList(varPaginatedMerchantPaidOrderListList)

	return err
}

type NullablePaginatedMerchantPaidOrderListList struct {
	value *PaginatedMerchantPaidOrderListList
	isSet bool
}

func (v NullablePaginatedMerchantPaidOrderListList) Get() *PaginatedMerchantPaidOrderListList {
	return v.value
}

func (v *NullablePaginatedMerchantPaidOrderListList) Set(val *PaginatedMerchantPaidOrderListList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedMerchantPaidOrderListList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedMerchantPaidOrderListList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedMerchantPaidOrderListList(val *PaginatedMerchantPaidOrderListList) *NullablePaginatedMerchantPaidOrderListList {
	return &NullablePaginatedMerchantPaidOrderListList{value: val, isSet: true}
}

func (v NullablePaginatedMerchantPaidOrderListList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedMerchantPaidOrderListList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


