/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
)

// checks if the RefundOrder type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefundOrder{}

// RefundOrder Serializer for refunding an order.
type RefundOrder struct {
	// Optional reason for the refund
	Reason *string `json:"reason,omitempty"`
}

// NewRefundOrder instantiates a new RefundOrder object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefundOrder() *RefundOrder {
	this := RefundOrder{}
	return &this
}

// NewRefundOrderWithDefaults instantiates a new RefundOrder object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefundOrderWithDefaults() *RefundOrder {
	this := RefundOrder{}
	return &this
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *RefundOrder) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundOrder) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *RefundOrder) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *RefundOrder) SetReason(v string) {
	o.Reason = &v
}

func (o RefundOrder) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefundOrder) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

type NullableRefundOrder struct {
	value *RefundOrder
	isSet bool
}

func (v NullableRefundOrder) Get() *RefundOrder {
	return v.value
}

func (v *NullableRefundOrder) Set(val *RefundOrder) {
	v.value = val
	v.isSet = true
}

func (v NullableRefundOrder) IsSet() bool {
	return v.isSet
}

func (v *NullableRefundOrder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefundOrder(val *RefundOrder) *NullableRefundOrder {
	return &NullableRefundOrder{value: val, isSet: true}
}

func (v NullableRefundOrder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefundOrder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


