/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WalletBalance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WalletBalance{}

// WalletBalance struct for WalletBalance
type WalletBalance struct {
	// Current wallet balance in Tomans
	Amount *int32 `json:"amount,omitempty"`
	// Deadline for settling negative balance
	NegativeSettlementDeadline NullableString `json:"negative_settlement_deadline"`
}

type _WalletBalance WalletBalance

// NewWalletBalance instantiates a new WalletBalance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWalletBalance(negativeSettlementDeadline NullableString) *WalletBalance {
	this := WalletBalance{}
	this.NegativeSettlementDeadline = negativeSettlementDeadline
	return &this
}

// NewWalletBalanceWithDefaults instantiates a new WalletBalance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWalletBalanceWithDefaults() *WalletBalance {
	this := WalletBalance{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *WalletBalance) GetAmount() int32 {
	if o == nil || IsNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WalletBalance) GetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *WalletBalance) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *WalletBalance) SetAmount(v int32) {
	o.Amount = &v
}

// GetNegativeSettlementDeadline returns the NegativeSettlementDeadline field value
// If the value is explicit nil, the zero value for string will be returned
func (o *WalletBalance) GetNegativeSettlementDeadline() string {
	if o == nil || o.NegativeSettlementDeadline.Get() == nil {
		var ret string
		return ret
	}

	return *o.NegativeSettlementDeadline.Get()
}

// GetNegativeSettlementDeadlineOk returns a tuple with the NegativeSettlementDeadline field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WalletBalance) GetNegativeSettlementDeadlineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NegativeSettlementDeadline.Get(), o.NegativeSettlementDeadline.IsSet()
}

// SetNegativeSettlementDeadline sets field value
func (o *WalletBalance) SetNegativeSettlementDeadline(v string) {
	o.NegativeSettlementDeadline.Set(&v)
}

func (o WalletBalance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WalletBalance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	toSerialize["negative_settlement_deadline"] = o.NegativeSettlementDeadline.Get()
	return toSerialize, nil
}

func (o *WalletBalance) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"negative_settlement_deadline",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWalletBalance := _WalletBalance{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWalletBalance)

	if err != nil {
		return err
	}

	*o = WalletBalance(varWalletBalance)

	return err
}

type NullableWalletBalance struct {
	value *WalletBalance
	isSet bool
}

func (v NullableWalletBalance) Get() *WalletBalance {
	return v.value
}

func (v *NullableWalletBalance) Set(val *WalletBalance) {
	v.value = val
	v.isSet = true
}

func (v NullableWalletBalance) IsSet() bool {
	return v.isSet
}

func (v *NullableWalletBalance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWalletBalance(val *WalletBalance) *NullableWalletBalance {
	return &NullableWalletBalance{value: val, isSet: true}
}

func (v NullableWalletBalance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWalletBalance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


