/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateOrderStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOrderStatus{}

// UpdateOrderStatus struct for UpdateOrderStatus
type UpdateOrderStatus struct {
	// Status to update the order to  * `1` - اولیه * `2` - شروع شده * `3` - در انتظار * `4` - در انتظار درگاه * `5` - منقضی شده * `6` - لغو شده * `7` - پرداخت‌شده توسط کاربر * `8` - پرداخت موفیت آمیز نبود * `9` - تأیید شده توسط فروشگاه * `10` - تأیید توسط فروشگاه ناموفق بود * `11` - ناموفق از سوی فروشگاه * `12` - لغوشده توسط فروشگاه * `13` - درخواست بازگشت وجه به مشتری به دلیل درخواست مشتری * `14` - درخواست بازگشت وجه به فروشگاه پس از عدم تأیید توسط فروشگاه * `15` - درخواست بازگشت وجه به مشتری پس از ناموفق بودن توسط فروشگاه * `16` - بازپرداخت به فروشگاه پس از لغو توسط فروشگاه * `17` - بازپرداخت تکمیل شد * `18` - زمان انقضا گذشته است * `19` - تحویل شده * `20` - جمع اوری شده و در حال ارسال
	Status OrderStatusEnum `json:"status"`
}

type _UpdateOrderStatus UpdateOrderStatus

// NewUpdateOrderStatus instantiates a new UpdateOrderStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOrderStatus(status OrderStatusEnum) *UpdateOrderStatus {
	this := UpdateOrderStatus{}
	this.Status = status
	return &this
}

// NewUpdateOrderStatusWithDefaults instantiates a new UpdateOrderStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOrderStatusWithDefaults() *UpdateOrderStatus {
	this := UpdateOrderStatus{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdateOrderStatus) GetStatus() OrderStatusEnum {
	if o == nil {
		var ret OrderStatusEnum
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateOrderStatus) GetStatusOk() (*OrderStatusEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateOrderStatus) SetStatus(v OrderStatusEnum) {
	o.Status = v
}

func (o UpdateOrderStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOrderStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *UpdateOrderStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOrderStatus := _UpdateOrderStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateOrderStatus)

	if err != nil {
		return err
	}

	*o = UpdateOrderStatus(varUpdateOrderStatus)

	return err
}

type NullableUpdateOrderStatus struct {
	value *UpdateOrderStatus
	isSet bool
}

func (v NullableUpdateOrderStatus) Get() *UpdateOrderStatus {
	return v.value
}

func (v *NullableUpdateOrderStatus) Set(val *UpdateOrderStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOrderStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOrderStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOrderStatus(val *UpdateOrderStatus) *NullableUpdateOrderStatus {
	return &NullableUpdateOrderStatus{value: val, isSet: true}
}

func (v NullableUpdateOrderStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOrderStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


