/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaymentOrder type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentOrder{}

// PaymentOrder struct for PaymentOrder
type PaymentOrder struct {
	FinalAmount int32 `json:"final_amount"`
	GatewayType GatewayTypeEnum `json:"gateway_type"`
	GatewayTypeDisplay string `json:"gateway_type_display"`
	PaidAt string `json:"paid_at"`
	GatewayName NullableString `json:"gateway_name"`
	InvoiceId NullableString `json:"invoice_id"`
	SettlementDate string `json:"settlement_date"`
	SettlementStatus int32 `json:"settlement_status"`
	SettlementStatusDisplay string `json:"settlement_status_display"`
}

type _PaymentOrder PaymentOrder

// NewPaymentOrder instantiates a new PaymentOrder object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentOrder(finalAmount int32, gatewayType GatewayTypeEnum, gatewayTypeDisplay string, paidAt string, gatewayName NullableString, invoiceId NullableString, settlementDate string, settlementStatus int32, settlementStatusDisplay string) *PaymentOrder {
	this := PaymentOrder{}
	this.FinalAmount = finalAmount
	this.GatewayType = gatewayType
	this.GatewayTypeDisplay = gatewayTypeDisplay
	this.PaidAt = paidAt
	this.GatewayName = gatewayName
	this.InvoiceId = invoiceId
	this.SettlementDate = settlementDate
	this.SettlementStatus = settlementStatus
	this.SettlementStatusDisplay = settlementStatusDisplay
	return &this
}

// NewPaymentOrderWithDefaults instantiates a new PaymentOrder object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentOrderWithDefaults() *PaymentOrder {
	this := PaymentOrder{}
	return &this
}

// GetFinalAmount returns the FinalAmount field value
func (o *PaymentOrder) GetFinalAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FinalAmount
}

// GetFinalAmountOk returns a tuple with the FinalAmount field value
// and a boolean to check if the value has been set.
func (o *PaymentOrder) GetFinalAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FinalAmount, true
}

// SetFinalAmount sets field value
func (o *PaymentOrder) SetFinalAmount(v int32) {
	o.FinalAmount = v
}

// GetGatewayType returns the GatewayType field value
func (o *PaymentOrder) GetGatewayType() GatewayTypeEnum {
	if o == nil {
		var ret GatewayTypeEnum
		return ret
	}

	return o.GatewayType
}

// GetGatewayTypeOk returns a tuple with the GatewayType field value
// and a boolean to check if the value has been set.
func (o *PaymentOrder) GetGatewayTypeOk() (*GatewayTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GatewayType, true
}

// SetGatewayType sets field value
func (o *PaymentOrder) SetGatewayType(v GatewayTypeEnum) {
	o.GatewayType = v
}

// GetGatewayTypeDisplay returns the GatewayTypeDisplay field value
func (o *PaymentOrder) GetGatewayTypeDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GatewayTypeDisplay
}

// GetGatewayTypeDisplayOk returns a tuple with the GatewayTypeDisplay field value
// and a boolean to check if the value has been set.
func (o *PaymentOrder) GetGatewayTypeDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GatewayTypeDisplay, true
}

// SetGatewayTypeDisplay sets field value
func (o *PaymentOrder) SetGatewayTypeDisplay(v string) {
	o.GatewayTypeDisplay = v
}

// GetPaidAt returns the PaidAt field value
func (o *PaymentOrder) GetPaidAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaidAt
}

// GetPaidAtOk returns a tuple with the PaidAt field value
// and a boolean to check if the value has been set.
func (o *PaymentOrder) GetPaidAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaidAt, true
}

// SetPaidAt sets field value
func (o *PaymentOrder) SetPaidAt(v string) {
	o.PaidAt = v
}

// GetGatewayName returns the GatewayName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PaymentOrder) GetGatewayName() string {
	if o == nil || o.GatewayName.Get() == nil {
		var ret string
		return ret
	}

	return *o.GatewayName.Get()
}

// GetGatewayNameOk returns a tuple with the GatewayName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentOrder) GetGatewayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GatewayName.Get(), o.GatewayName.IsSet()
}

// SetGatewayName sets field value
func (o *PaymentOrder) SetGatewayName(v string) {
	o.GatewayName.Set(&v)
}

// GetInvoiceId returns the InvoiceId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PaymentOrder) GetInvoiceId() string {
	if o == nil || o.InvoiceId.Get() == nil {
		var ret string
		return ret
	}

	return *o.InvoiceId.Get()
}

// GetInvoiceIdOk returns a tuple with the InvoiceId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaymentOrder) GetInvoiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InvoiceId.Get(), o.InvoiceId.IsSet()
}

// SetInvoiceId sets field value
func (o *PaymentOrder) SetInvoiceId(v string) {
	o.InvoiceId.Set(&v)
}

// GetSettlementDate returns the SettlementDate field value
func (o *PaymentOrder) GetSettlementDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SettlementDate
}

// GetSettlementDateOk returns a tuple with the SettlementDate field value
// and a boolean to check if the value has been set.
func (o *PaymentOrder) GetSettlementDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettlementDate, true
}

// SetSettlementDate sets field value
func (o *PaymentOrder) SetSettlementDate(v string) {
	o.SettlementDate = v
}

// GetSettlementStatus returns the SettlementStatus field value
func (o *PaymentOrder) GetSettlementStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SettlementStatus
}

// GetSettlementStatusOk returns a tuple with the SettlementStatus field value
// and a boolean to check if the value has been set.
func (o *PaymentOrder) GetSettlementStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettlementStatus, true
}

// SetSettlementStatus sets field value
func (o *PaymentOrder) SetSettlementStatus(v int32) {
	o.SettlementStatus = v
}

// GetSettlementStatusDisplay returns the SettlementStatusDisplay field value
func (o *PaymentOrder) GetSettlementStatusDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SettlementStatusDisplay
}

// GetSettlementStatusDisplayOk returns a tuple with the SettlementStatusDisplay field value
// and a boolean to check if the value has been set.
func (o *PaymentOrder) GetSettlementStatusDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettlementStatusDisplay, true
}

// SetSettlementStatusDisplay sets field value
func (o *PaymentOrder) SetSettlementStatusDisplay(v string) {
	o.SettlementStatusDisplay = v
}

func (o PaymentOrder) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentOrder) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["final_amount"] = o.FinalAmount
	toSerialize["gateway_type"] = o.GatewayType
	toSerialize["gateway_type_display"] = o.GatewayTypeDisplay
	toSerialize["paid_at"] = o.PaidAt
	toSerialize["gateway_name"] = o.GatewayName.Get()
	toSerialize["invoice_id"] = o.InvoiceId.Get()
	toSerialize["settlement_date"] = o.SettlementDate
	toSerialize["settlement_status"] = o.SettlementStatus
	toSerialize["settlement_status_display"] = o.SettlementStatusDisplay
	return toSerialize, nil
}

func (o *PaymentOrder) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"final_amount",
		"gateway_type",
		"gateway_type_display",
		"paid_at",
		"gateway_name",
		"invoice_id",
		"settlement_date",
		"settlement_status",
		"settlement_status_display",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentOrder := _PaymentOrder{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaymentOrder)

	if err != nil {
		return err
	}

	*o = PaymentOrder(varPaymentOrder)

	return err
}

type NullablePaymentOrder struct {
	value *PaymentOrder
	isSet bool
}

func (v NullablePaymentOrder) Get() *PaymentOrder {
	return v.value
}

func (v *NullablePaymentOrder) Set(val *PaymentOrder) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentOrder) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentOrder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentOrder(val *PaymentOrder) *NullablePaymentOrder {
	return &NullablePaymentOrder{value: val, isSet: true}
}

func (v NullablePaymentOrder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentOrder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


