/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
)

// checks if the OrderUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderUser{}

// OrderUser struct for OrderUser
type OrderUser struct {
	FirstName *string `json:"first_name,omitempty"`
	LastName *string `json:"last_name,omitempty"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	NationalIdentityNumber NullableString `json:"national_identity_number,omitempty"`
	BirthDate NullableString `json:"birth_date,omitempty"`
}

// NewOrderUser instantiates a new OrderUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderUser() *OrderUser {
	this := OrderUser{}
	return &this
}

// NewOrderUserWithDefaults instantiates a new OrderUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderUserWithDefaults() *OrderUser {
	this := OrderUser{}
	return &this
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *OrderUser) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderUser) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *OrderUser) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *OrderUser) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *OrderUser) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderUser) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *OrderUser) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *OrderUser) SetLastName(v string) {
	o.LastName = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *OrderUser) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderUser) GetPhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *OrderUser) HasPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *OrderUser) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetNationalIdentityNumber returns the NationalIdentityNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrderUser) GetNationalIdentityNumber() string {
	if o == nil || IsNil(o.NationalIdentityNumber.Get()) {
		var ret string
		return ret
	}
	return *o.NationalIdentityNumber.Get()
}

// GetNationalIdentityNumberOk returns a tuple with the NationalIdentityNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrderUser) GetNationalIdentityNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NationalIdentityNumber.Get(), o.NationalIdentityNumber.IsSet()
}

// HasNationalIdentityNumber returns a boolean if a field has been set.
func (o *OrderUser) HasNationalIdentityNumber() bool {
	if o != nil && o.NationalIdentityNumber.IsSet() {
		return true
	}

	return false
}

// SetNationalIdentityNumber gets a reference to the given NullableString and assigns it to the NationalIdentityNumber field.
func (o *OrderUser) SetNationalIdentityNumber(v string) {
	o.NationalIdentityNumber.Set(&v)
}
// SetNationalIdentityNumberNil sets the value for NationalIdentityNumber to be an explicit nil
func (o *OrderUser) SetNationalIdentityNumberNil() {
	o.NationalIdentityNumber.Set(nil)
}

// UnsetNationalIdentityNumber ensures that no value is present for NationalIdentityNumber, not even an explicit nil
func (o *OrderUser) UnsetNationalIdentityNumber() {
	o.NationalIdentityNumber.Unset()
}

// GetBirthDate returns the BirthDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrderUser) GetBirthDate() string {
	if o == nil || IsNil(o.BirthDate.Get()) {
		var ret string
		return ret
	}
	return *o.BirthDate.Get()
}

// GetBirthDateOk returns a tuple with the BirthDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrderUser) GetBirthDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BirthDate.Get(), o.BirthDate.IsSet()
}

// HasBirthDate returns a boolean if a field has been set.
func (o *OrderUser) HasBirthDate() bool {
	if o != nil && o.BirthDate.IsSet() {
		return true
	}

	return false
}

// SetBirthDate gets a reference to the given NullableString and assigns it to the BirthDate field.
func (o *OrderUser) SetBirthDate(v string) {
	o.BirthDate.Set(&v)
}
// SetBirthDateNil sets the value for BirthDate to be an explicit nil
func (o *OrderUser) SetBirthDateNil() {
	o.BirthDate.Set(nil)
}

// UnsetBirthDate ensures that no value is present for BirthDate, not even an explicit nil
func (o *OrderUser) UnsetBirthDate() {
	o.BirthDate.Unset()
}

func (o OrderUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if !IsNil(o.PhoneNumber) {
		toSerialize["phone_number"] = o.PhoneNumber
	}
	if o.NationalIdentityNumber.IsSet() {
		toSerialize["national_identity_number"] = o.NationalIdentityNumber.Get()
	}
	if o.BirthDate.IsSet() {
		toSerialize["birth_date"] = o.BirthDate.Get()
	}
	return toSerialize, nil
}

type NullableOrderUser struct {
	value *OrderUser
	isSet bool
}

func (v NullableOrderUser) Get() *OrderUser {
	return v.value
}

func (v *NullableOrderUser) Set(val *OrderUser) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderUser) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderUser(val *OrderUser) *NullableOrderUser {
	return &NullableOrderUser{value: val, isSet: true}
}

func (v NullableOrderUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


