/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the MerchantPaidOrderList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MerchantPaidOrderList{}

// MerchantPaidOrderList Serializer for manager view listing PAID_BY_USER orders
type MerchantPaidOrderList struct {
	OrderUuid string `json:"order_uuid"`
	// شناسه منحصر به فرد سفارش در سیستم فروشنده
	MerchantOrderId string `json:"merchant_order_id"`
	// شناسه منحصر به فرد فروشنده برای تأیید سفارش
	MerchantUniqueId string `json:"merchant_unique_id"`
	PaidAt NullableTime `json:"paid_at"`
	RefundsAt NullableTime `json:"refunds_at"`
}

type _MerchantPaidOrderList MerchantPaidOrderList

// NewMerchantPaidOrderList instantiates a new MerchantPaidOrderList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMerchantPaidOrderList(orderUuid string, merchantOrderId string, merchantUniqueId string, paidAt NullableTime, refundsAt NullableTime) *MerchantPaidOrderList {
	this := MerchantPaidOrderList{}
	this.OrderUuid = orderUuid
	this.MerchantOrderId = merchantOrderId
	this.MerchantUniqueId = merchantUniqueId
	this.PaidAt = paidAt
	this.RefundsAt = refundsAt
	return &this
}

// NewMerchantPaidOrderListWithDefaults instantiates a new MerchantPaidOrderList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMerchantPaidOrderListWithDefaults() *MerchantPaidOrderList {
	this := MerchantPaidOrderList{}
	return &this
}

// GetOrderUuid returns the OrderUuid field value
func (o *MerchantPaidOrderList) GetOrderUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderUuid
}

// GetOrderUuidOk returns a tuple with the OrderUuid field value
// and a boolean to check if the value has been set.
func (o *MerchantPaidOrderList) GetOrderUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderUuid, true
}

// SetOrderUuid sets field value
func (o *MerchantPaidOrderList) SetOrderUuid(v string) {
	o.OrderUuid = v
}

// GetMerchantOrderId returns the MerchantOrderId field value
func (o *MerchantPaidOrderList) GetMerchantOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MerchantOrderId
}

// GetMerchantOrderIdOk returns a tuple with the MerchantOrderId field value
// and a boolean to check if the value has been set.
func (o *MerchantPaidOrderList) GetMerchantOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MerchantOrderId, true
}

// SetMerchantOrderId sets field value
func (o *MerchantPaidOrderList) SetMerchantOrderId(v string) {
	o.MerchantOrderId = v
}

// GetMerchantUniqueId returns the MerchantUniqueId field value
func (o *MerchantPaidOrderList) GetMerchantUniqueId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MerchantUniqueId
}

// GetMerchantUniqueIdOk returns a tuple with the MerchantUniqueId field value
// and a boolean to check if the value has been set.
func (o *MerchantPaidOrderList) GetMerchantUniqueIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MerchantUniqueId, true
}

// SetMerchantUniqueId sets field value
func (o *MerchantPaidOrderList) SetMerchantUniqueId(v string) {
	o.MerchantUniqueId = v
}

// GetPaidAt returns the PaidAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *MerchantPaidOrderList) GetPaidAt() time.Time {
	if o == nil || o.PaidAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.PaidAt.Get()
}

// GetPaidAtOk returns a tuple with the PaidAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MerchantPaidOrderList) GetPaidAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.PaidAt.Get(), o.PaidAt.IsSet()
}

// SetPaidAt sets field value
func (o *MerchantPaidOrderList) SetPaidAt(v time.Time) {
	o.PaidAt.Set(&v)
}

// GetRefundsAt returns the RefundsAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *MerchantPaidOrderList) GetRefundsAt() time.Time {
	if o == nil || o.RefundsAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.RefundsAt.Get()
}

// GetRefundsAtOk returns a tuple with the RefundsAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MerchantPaidOrderList) GetRefundsAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RefundsAt.Get(), o.RefundsAt.IsSet()
}

// SetRefundsAt sets field value
func (o *MerchantPaidOrderList) SetRefundsAt(v time.Time) {
	o.RefundsAt.Set(&v)
}

func (o MerchantPaidOrderList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MerchantPaidOrderList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["order_uuid"] = o.OrderUuid
	toSerialize["merchant_order_id"] = o.MerchantOrderId
	toSerialize["merchant_unique_id"] = o.MerchantUniqueId
	toSerialize["paid_at"] = o.PaidAt.Get()
	toSerialize["refunds_at"] = o.RefundsAt.Get()
	return toSerialize, nil
}

func (o *MerchantPaidOrderList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"order_uuid",
		"merchant_order_id",
		"merchant_unique_id",
		"paid_at",
		"refunds_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMerchantPaidOrderList := _MerchantPaidOrderList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMerchantPaidOrderList)

	if err != nil {
		return err
	}

	*o = MerchantPaidOrderList(varMerchantPaidOrderList)

	return err
}

type NullableMerchantPaidOrderList struct {
	value *MerchantPaidOrderList
	isSet bool
}

func (v NullableMerchantPaidOrderList) Get() *MerchantPaidOrderList {
	return v.value
}

func (v *NullableMerchantPaidOrderList) Set(val *MerchantPaidOrderList) {
	v.value = val
	v.isSet = true
}

func (v NullableMerchantPaidOrderList) IsSet() bool {
	return v.isSet
}

func (v *NullableMerchantPaidOrderList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMerchantPaidOrderList(val *MerchantPaidOrderList) *NullableMerchantPaidOrderList {
	return &NullableMerchantPaidOrderList{value: val, isSet: true}
}

func (v NullableMerchantPaidOrderList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMerchantPaidOrderList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


