/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"fmt"
)

// ErrorEnum * `User is not authenticated.` - کاربر تأیید هویت نشده است. * `Order not found.` - Order not found. * `Order is not in a state where shipping can be selected.` - سفارش در وضعیتی نیست که بتوان روش ارسال را انتخاب کرد. * `Order is not in a state where packing can be selected.` - سفارش در وضعیتی نیست که بتوان بسته‌بندی را انتخاب کرد. * `Failed to initiate refund. Please try again later.` - عملیات بازپرداخت ناموفق بود. لطفاً بعداً دوباره امتحان کنید. * `Order is expired or cancelled.` - سفارش منقضی‌شده یا لغو‌شده است. * `Invalid request origin.` - Invalid request origin. * `Digi Express shipping method not found.` - روش ارسال دیجی اکسپرس یافت نشد. * `Order address not found.` - آدرس سفارش یافت نشد. * `Failed to fetch Digi Express shipping time window options.` - دریافت گزینه‌های بازه زمانی ارسال دیجی اکسپرس ناموفق بود. * `Address ID not found.` - Address ID not found. * `Failed to cancel shipment.` - خطا در کنسل کردن مرسوله. * `Failed to cancel shipment in third party service.` - خطا در کنسل کردن مرسوله از سمت سرویس خارجی. * `Shipment not found.` - Shipment not found. * `Selected shipping method is not eligible for cancellation.` - Selected shipping method is not eligible for cancellation. * `DigiExpress shipment is not in cancelable in this state` - مرسوله دیجی‌اکسپرس در این وضعیت قابل کنسل شدن نیست. * `DigiExpress shipment is not in reviveable in this state` - مرسوله دیجی‌اکسپرس در این وضعیت قابل ارسال مجدد نیست. * `Failed to revive shipment in third party service.` - Failed to revive shipment in third party service. * `Selected shipping method is not eligible for revival.` - Selected shipping method is not eligible for revival.
type ErrorEnum string

// List of ErrorEnum
const (
	USER_IS_NOT_AUTHENTICATED ErrorEnum = "User is not authenticated."
	ORDER_NOT_FOUND ErrorEnum = "Order not found."
	ORDER_IS_NOT_IN_A_STATE_WHERE_SHIPPING_CAN_BE_SELECTED ErrorEnum = "Order is not in a state where shipping can be selected."
	ORDER_IS_NOT_IN_A_STATE_WHERE_PACKING_CAN_BE_SELECTED ErrorEnum = "Order is not in a state where packing can be selected."
	FAILED_TO_INITIATE_REFUND__PLEASE_TRY_AGAIN_LATER ErrorEnum = "Failed to initiate refund. Please try again later."
	ORDER_IS_EXPIRED_OR_CANCELLED ErrorEnum = "Order is expired or cancelled."
	INVALID_REQUEST_ORIGIN ErrorEnum = "Invalid request origin."
	DIGI_EXPRESS_SHIPPING_METHOD_NOT_FOUND ErrorEnum = "Digi Express shipping method not found."
	ORDER_ADDRESS_NOT_FOUND ErrorEnum = "Order address not found."
	FAILED_TO_FETCH_DIGI_EXPRESS_SHIPPING_TIME_WINDOW_OPTIONS ErrorEnum = "Failed to fetch Digi Express shipping time window options."
	ADDRESS_ID_NOT_FOUND ErrorEnum = "Address ID not found."
	FAILED_TO_CANCEL_SHIPMENT ErrorEnum = "Failed to cancel shipment."
	FAILED_TO_CANCEL_SHIPMENT_IN_THIRD_PARTY_SERVICE ErrorEnum = "Failed to cancel shipment in third party service."
	SHIPMENT_NOT_FOUND ErrorEnum = "Shipment not found."
	SELECTED_SHIPPING_METHOD_IS_NOT_ELIGIBLE_FOR_CANCELLATION ErrorEnum = "Selected shipping method is not eligible for cancellation."
	DIGI_EXPRESS_SHIPMENT_IS_NOT_IN_CANCELABLE_IN_THIS_STATE ErrorEnum = "DigiExpress shipment is not in cancelable in this state"
	DIGI_EXPRESS_SHIPMENT_IS_NOT_IN_REVIVEABLE_IN_THIS_STATE ErrorEnum = "DigiExpress shipment is not in reviveable in this state"
	FAILED_TO_REVIVE_SHIPMENT_IN_THIRD_PARTY_SERVICE ErrorEnum = "Failed to revive shipment in third party service."
	SELECTED_SHIPPING_METHOD_IS_NOT_ELIGIBLE_FOR_REVIVAL ErrorEnum = "Selected shipping method is not eligible for revival."
)

// All allowed values of ErrorEnum enum
var AllowedErrorEnumEnumValues = []ErrorEnum{
	"User is not authenticated.",
	"Order not found.",
	"Order is not in a state where shipping can be selected.",
	"Order is not in a state where packing can be selected.",
	"Failed to initiate refund. Please try again later.",
	"Order is expired or cancelled.",
	"Invalid request origin.",
	"Digi Express shipping method not found.",
	"Order address not found.",
	"Failed to fetch Digi Express shipping time window options.",
	"Address ID not found.",
	"Failed to cancel shipment.",
	"Failed to cancel shipment in third party service.",
	"Shipment not found.",
	"Selected shipping method is not eligible for cancellation.",
	"DigiExpress shipment is not in cancelable in this state",
	"DigiExpress shipment is not in reviveable in this state",
	"Failed to revive shipment in third party service.",
	"Selected shipping method is not eligible for revival.",
}

func (v *ErrorEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ErrorEnum(value)
	for _, existing := range AllowedErrorEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ErrorEnum", value)
}

// NewErrorEnumFromValue returns a pointer to a valid ErrorEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewErrorEnumFromValue(v string) (*ErrorEnum, error) {
	ev := ErrorEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ErrorEnum: valid values are %v", v, AllowedErrorEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ErrorEnum) IsValid() bool {
	for _, existing := range AllowedErrorEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ErrorEnum value
func (v ErrorEnum) Ptr() *ErrorEnum {
	return &v
}

type NullableErrorEnum struct {
	value *ErrorEnum
	isSet bool
}

func (v NullableErrorEnum) Get() *ErrorEnum {
	return v.value
}

func (v *NullableErrorEnum) Set(val *ErrorEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorEnum(val *ErrorEnum) *NullableErrorEnum {
	return &NullableErrorEnum{value: val, isSet: true}
}

func (v NullableErrorEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

