/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"fmt"
)

// GatewayTypeEnum * `1` - آنلاین * `2` - BNPL (الان بخر، بعداً پرداخت کن) * `3` - اعتباری * `4` - کیف پول دیجی‌پی * `5` - اقساط پیش‌فرض
type GatewayTypeEnum int32

// List of GatewayTypeEnum
const (
	_1 GatewayTypeEnum = 1
	_2 GatewayTypeEnum = 2
	_3 GatewayTypeEnum = 3
	_4 GatewayTypeEnum = 4
	_5 GatewayTypeEnum = 5
)

// All allowed values of GatewayTypeEnum enum
var AllowedGatewayTypeEnumEnumValues = []GatewayTypeEnum{
	1,
	2,
	3,
	4,
	5,
}

func (v *GatewayTypeEnum) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GatewayTypeEnum(value)
	for _, existing := range AllowedGatewayTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GatewayTypeEnum", value)
}

// NewGatewayTypeEnumFromValue returns a pointer to a valid GatewayTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGatewayTypeEnumFromValue(v int32) (*GatewayTypeEnum, error) {
	ev := GatewayTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GatewayTypeEnum: valid values are %v", v, AllowedGatewayTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GatewayTypeEnum) IsValid() bool {
	for _, existing := range AllowedGatewayTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to GatewayTypeEnum value
func (v GatewayTypeEnum) Ptr() *GatewayTypeEnum {
	return &v
}

type NullableGatewayTypeEnum struct {
	value *GatewayTypeEnum
	isSet bool
}

func (v NullableGatewayTypeEnum) Get() *GatewayTypeEnum {
	return v.value
}

func (v *NullableGatewayTypeEnum) Set(val *GatewayTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayTypeEnum(val *GatewayTypeEnum) *NullableGatewayTypeEnum {
	return &NullableGatewayTypeEnum{value: val, isSet: true}
}

func (v NullableGatewayTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

