/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeliveryTimeRangeDisplay type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeliveryTimeRangeDisplay{}

// DeliveryTimeRangeDisplay struct for DeliveryTimeRangeDisplay
type DeliveryTimeRangeDisplay struct {
	MinDate string `json:"min_date"`
	MaxDate string `json:"max_date"`
}

type _DeliveryTimeRangeDisplay DeliveryTimeRangeDisplay

// NewDeliveryTimeRangeDisplay instantiates a new DeliveryTimeRangeDisplay object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliveryTimeRangeDisplay(minDate string, maxDate string) *DeliveryTimeRangeDisplay {
	this := DeliveryTimeRangeDisplay{}
	this.MinDate = minDate
	this.MaxDate = maxDate
	return &this
}

// NewDeliveryTimeRangeDisplayWithDefaults instantiates a new DeliveryTimeRangeDisplay object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryTimeRangeDisplayWithDefaults() *DeliveryTimeRangeDisplay {
	this := DeliveryTimeRangeDisplay{}
	return &this
}

// GetMinDate returns the MinDate field value
func (o *DeliveryTimeRangeDisplay) GetMinDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MinDate
}

// GetMinDateOk returns a tuple with the MinDate field value
// and a boolean to check if the value has been set.
func (o *DeliveryTimeRangeDisplay) GetMinDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinDate, true
}

// SetMinDate sets field value
func (o *DeliveryTimeRangeDisplay) SetMinDate(v string) {
	o.MinDate = v
}

// GetMaxDate returns the MaxDate field value
func (o *DeliveryTimeRangeDisplay) GetMaxDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MaxDate
}

// GetMaxDateOk returns a tuple with the MaxDate field value
// and a boolean to check if the value has been set.
func (o *DeliveryTimeRangeDisplay) GetMaxDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxDate, true
}

// SetMaxDate sets field value
func (o *DeliveryTimeRangeDisplay) SetMaxDate(v string) {
	o.MaxDate = v
}

func (o DeliveryTimeRangeDisplay) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeliveryTimeRangeDisplay) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["min_date"] = o.MinDate
	toSerialize["max_date"] = o.MaxDate
	return toSerialize, nil
}

func (o *DeliveryTimeRangeDisplay) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"min_date",
		"max_date",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeliveryTimeRangeDisplay := _DeliveryTimeRangeDisplay{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeliveryTimeRangeDisplay)

	if err != nil {
		return err
	}

	*o = DeliveryTimeRangeDisplay(varDeliveryTimeRangeDisplay)

	return err
}

type NullableDeliveryTimeRangeDisplay struct {
	value *DeliveryTimeRangeDisplay
	isSet bool
}

func (v NullableDeliveryTimeRangeDisplay) Get() *DeliveryTimeRangeDisplay {
	return v.value
}

func (v *NullableDeliveryTimeRangeDisplay) Set(val *DeliveryTimeRangeDisplay) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliveryTimeRangeDisplay) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliveryTimeRangeDisplay) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliveryTimeRangeDisplay(val *DeliveryTimeRangeDisplay) *NullableDeliveryTimeRangeDisplay {
	return &NullableDeliveryTimeRangeDisplay{value: val, isSet: true}
}

func (v NullableDeliveryTimeRangeDisplay) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliveryTimeRangeDisplay) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


