/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"fmt"
)

// ShippingTypeEnum * `1` - سایر * `2` - دیجی اکسپرس
type ShippingTypeEnum int32

// List of ShippingTypeEnum
const (
	_1 ShippingTypeEnum = 1
	_2 ShippingTypeEnum = 2
)

// All allowed values of ShippingTypeEnum enum
var AllowedShippingTypeEnumEnumValues = []ShippingTypeEnum{
	1,
	2,
}

func (v *ShippingTypeEnum) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ShippingTypeEnum(value)
	for _, existing := range AllowedShippingTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ShippingTypeEnum", value)
}

// NewShippingTypeEnumFromValue returns a pointer to a valid ShippingTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewShippingTypeEnumFromValue(v int32) (*ShippingTypeEnum, error) {
	ev := ShippingTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ShippingTypeEnum: valid values are %v", v, AllowedShippingTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ShippingTypeEnum) IsValid() bool {
	for _, existing := range AllowedShippingTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ShippingTypeEnum value
func (v ShippingTypeEnum) Ptr() *ShippingTypeEnum {
	return &v
}

type NullableShippingTypeEnum struct {
	value *ShippingTypeEnum
	isSet bool
}

func (v NullableShippingTypeEnum) Get() *ShippingTypeEnum {
	return v.value
}

func (v *NullableShippingTypeEnum) Set(val *ShippingTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableShippingTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableShippingTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShippingTypeEnum(val *ShippingTypeEnum) *NullableShippingTypeEnum {
	return &NullableShippingTypeEnum{value: val, isSet: true}
}

func (v NullableShippingTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShippingTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

