/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"fmt"
)

// TypeNameEnum * `color` - رنگ * `size` - اندازه * `warranty` - گارانتی * `weight` - وزن * `other` - سایر
type TypeNameEnum string

// List of TypeNameEnum
const (
	COLOR TypeNameEnum = "color"
	SIZE TypeNameEnum = "size"
	WARRANTY TypeNameEnum = "warranty"
	WEIGHT TypeNameEnum = "weight"
	OTHER TypeNameEnum = "other"
)

// All allowed values of TypeNameEnum enum
var AllowedTypeNameEnumEnumValues = []TypeNameEnum{
	"color",
	"size",
	"warranty",
	"weight",
	"other",
}

func (v *TypeNameEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TypeNameEnum(value)
	for _, existing := range AllowedTypeNameEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TypeNameEnum", value)
}

// NewTypeNameEnumFromValue returns a pointer to a valid TypeNameEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTypeNameEnumFromValue(v string) (*TypeNameEnum, error) {
	ev := TypeNameEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TypeNameEnum: valid values are %v", v, AllowedTypeNameEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TypeNameEnum) IsValid() bool {
	for _, existing := range AllowedTypeNameEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TypeNameEnum value
func (v TypeNameEnum) Ptr() *TypeNameEnum {
	return &v
}

type NullableTypeNameEnum struct {
	value *TypeNameEnum
	isSet bool
}

func (v NullableTypeNameEnum) Get() *TypeNameEnum {
	return v.value
}

func (v *NullableTypeNameEnum) Set(val *TypeNameEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableTypeNameEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableTypeNameEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypeNameEnum(val *TypeNameEnum) *NullableTypeNameEnum {
	return &NullableTypeNameEnum{value: val, isSet: true}
}

func (v NullableTypeNameEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypeNameEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

