/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ShippingMethod type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShippingMethod{}

// ShippingMethod Serializer for shipping method details.
type ShippingMethod struct {
	Id int32 `json:"id"`
	// نام روش ارسال
	Name string `json:"name"`
	// توضیحات روش ارسال و جزئیات تحویل آن
	Description *string `json:"description,omitempty"`
	// نوع روش ارسال: عادی یا دیجی اکسپرس  * `1` - سایر * `2` - دیجی اکسپرس
	ShippingType *ShippingTypeEnum `json:"shipping_type,omitempty"`
	GetShippingTypeDisplay string `json:"get_shipping_type_display"`
	ShippingTypeDisplay string `json:"shipping_type_display"`
	// هزینه ارسال برای منطقه اولیه (مثلاً تهران) به تومان
	Cost *int32 `json:"cost,omitempty"`
	// هزینه ارسال برای مناطق دیگر به تومان
	SecondaryCost *int32 `json:"secondary_cost,omitempty"`
	// حداقل تعداد روزها از تاریخ سفارش تا تحویل
	MinimumTimeSending *int32 `json:"minimum_time_sending,omitempty"`
	// حداکثر تعداد روزها از تاریخ سفارش تا تحویل
	MaximumTimeSending *int32 `json:"maximum_time_sending,omitempty"`
	DeliveryTimeDisplay string `json:"delivery_time_display"`
	DeliveryTimeRangeDisplay DeliveryTimeRangeDisplay `json:"delivery_time_range_display"`
	InventoryAddress BusinessAddress `json:"inventory_address"`
	// Whether the shipping method is pay at destination
	IsPayAtDestination *bool `json:"is_pay_at_destination,omitempty"`
}

type _ShippingMethod ShippingMethod

// NewShippingMethod instantiates a new ShippingMethod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShippingMethod(id int32, name string, getShippingTypeDisplay string, shippingTypeDisplay string, deliveryTimeDisplay string, deliveryTimeRangeDisplay DeliveryTimeRangeDisplay, inventoryAddress BusinessAddress) *ShippingMethod {
	this := ShippingMethod{}
	this.Id = id
	this.Name = name
	this.GetShippingTypeDisplay = getShippingTypeDisplay
	this.ShippingTypeDisplay = shippingTypeDisplay
	this.DeliveryTimeDisplay = deliveryTimeDisplay
	this.DeliveryTimeRangeDisplay = deliveryTimeRangeDisplay
	this.InventoryAddress = inventoryAddress
	return &this
}

// NewShippingMethodWithDefaults instantiates a new ShippingMethod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShippingMethodWithDefaults() *ShippingMethod {
	this := ShippingMethod{}
	return &this
}

// GetId returns the Id field value
func (o *ShippingMethod) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ShippingMethod) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ShippingMethod) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ShippingMethod) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ShippingMethod) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ShippingMethod) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ShippingMethod) SetDescription(v string) {
	o.Description = &v
}

// GetShippingType returns the ShippingType field value if set, zero value otherwise.
func (o *ShippingMethod) GetShippingType() ShippingTypeEnum {
	if o == nil || IsNil(o.ShippingType) {
		var ret ShippingTypeEnum
		return ret
	}
	return *o.ShippingType
}

// GetShippingTypeOk returns a tuple with the ShippingType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetShippingTypeOk() (*ShippingTypeEnum, bool) {
	if o == nil || IsNil(o.ShippingType) {
		return nil, false
	}
	return o.ShippingType, true
}

// HasShippingType returns a boolean if a field has been set.
func (o *ShippingMethod) HasShippingType() bool {
	if o != nil && !IsNil(o.ShippingType) {
		return true
	}

	return false
}

// SetShippingType gets a reference to the given ShippingTypeEnum and assigns it to the ShippingType field.
func (o *ShippingMethod) SetShippingType(v ShippingTypeEnum) {
	o.ShippingType = &v
}

// GetGetShippingTypeDisplay returns the GetShippingTypeDisplay field value
func (o *ShippingMethod) GetGetShippingTypeDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GetShippingTypeDisplay
}

// GetGetShippingTypeDisplayOk returns a tuple with the GetShippingTypeDisplay field value
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetGetShippingTypeDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GetShippingTypeDisplay, true
}

// SetGetShippingTypeDisplay sets field value
func (o *ShippingMethod) SetGetShippingTypeDisplay(v string) {
	o.GetShippingTypeDisplay = v
}

// GetShippingTypeDisplay returns the ShippingTypeDisplay field value
func (o *ShippingMethod) GetShippingTypeDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShippingTypeDisplay
}

// GetShippingTypeDisplayOk returns a tuple with the ShippingTypeDisplay field value
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetShippingTypeDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShippingTypeDisplay, true
}

// SetShippingTypeDisplay sets field value
func (o *ShippingMethod) SetShippingTypeDisplay(v string) {
	o.ShippingTypeDisplay = v
}

// GetCost returns the Cost field value if set, zero value otherwise.
func (o *ShippingMethod) GetCost() int32 {
	if o == nil || IsNil(o.Cost) {
		var ret int32
		return ret
	}
	return *o.Cost
}

// GetCostOk returns a tuple with the Cost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetCostOk() (*int32, bool) {
	if o == nil || IsNil(o.Cost) {
		return nil, false
	}
	return o.Cost, true
}

// HasCost returns a boolean if a field has been set.
func (o *ShippingMethod) HasCost() bool {
	if o != nil && !IsNil(o.Cost) {
		return true
	}

	return false
}

// SetCost gets a reference to the given int32 and assigns it to the Cost field.
func (o *ShippingMethod) SetCost(v int32) {
	o.Cost = &v
}

// GetSecondaryCost returns the SecondaryCost field value if set, zero value otherwise.
func (o *ShippingMethod) GetSecondaryCost() int32 {
	if o == nil || IsNil(o.SecondaryCost) {
		var ret int32
		return ret
	}
	return *o.SecondaryCost
}

// GetSecondaryCostOk returns a tuple with the SecondaryCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetSecondaryCostOk() (*int32, bool) {
	if o == nil || IsNil(o.SecondaryCost) {
		return nil, false
	}
	return o.SecondaryCost, true
}

// HasSecondaryCost returns a boolean if a field has been set.
func (o *ShippingMethod) HasSecondaryCost() bool {
	if o != nil && !IsNil(o.SecondaryCost) {
		return true
	}

	return false
}

// SetSecondaryCost gets a reference to the given int32 and assigns it to the SecondaryCost field.
func (o *ShippingMethod) SetSecondaryCost(v int32) {
	o.SecondaryCost = &v
}

// GetMinimumTimeSending returns the MinimumTimeSending field value if set, zero value otherwise.
func (o *ShippingMethod) GetMinimumTimeSending() int32 {
	if o == nil || IsNil(o.MinimumTimeSending) {
		var ret int32
		return ret
	}
	return *o.MinimumTimeSending
}

// GetMinimumTimeSendingOk returns a tuple with the MinimumTimeSending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetMinimumTimeSendingOk() (*int32, bool) {
	if o == nil || IsNil(o.MinimumTimeSending) {
		return nil, false
	}
	return o.MinimumTimeSending, true
}

// HasMinimumTimeSending returns a boolean if a field has been set.
func (o *ShippingMethod) HasMinimumTimeSending() bool {
	if o != nil && !IsNil(o.MinimumTimeSending) {
		return true
	}

	return false
}

// SetMinimumTimeSending gets a reference to the given int32 and assigns it to the MinimumTimeSending field.
func (o *ShippingMethod) SetMinimumTimeSending(v int32) {
	o.MinimumTimeSending = &v
}

// GetMaximumTimeSending returns the MaximumTimeSending field value if set, zero value otherwise.
func (o *ShippingMethod) GetMaximumTimeSending() int32 {
	if o == nil || IsNil(o.MaximumTimeSending) {
		var ret int32
		return ret
	}
	return *o.MaximumTimeSending
}

// GetMaximumTimeSendingOk returns a tuple with the MaximumTimeSending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetMaximumTimeSendingOk() (*int32, bool) {
	if o == nil || IsNil(o.MaximumTimeSending) {
		return nil, false
	}
	return o.MaximumTimeSending, true
}

// HasMaximumTimeSending returns a boolean if a field has been set.
func (o *ShippingMethod) HasMaximumTimeSending() bool {
	if o != nil && !IsNil(o.MaximumTimeSending) {
		return true
	}

	return false
}

// SetMaximumTimeSending gets a reference to the given int32 and assigns it to the MaximumTimeSending field.
func (o *ShippingMethod) SetMaximumTimeSending(v int32) {
	o.MaximumTimeSending = &v
}

// GetDeliveryTimeDisplay returns the DeliveryTimeDisplay field value
func (o *ShippingMethod) GetDeliveryTimeDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeliveryTimeDisplay
}

// GetDeliveryTimeDisplayOk returns a tuple with the DeliveryTimeDisplay field value
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetDeliveryTimeDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeliveryTimeDisplay, true
}

// SetDeliveryTimeDisplay sets field value
func (o *ShippingMethod) SetDeliveryTimeDisplay(v string) {
	o.DeliveryTimeDisplay = v
}

// GetDeliveryTimeRangeDisplay returns the DeliveryTimeRangeDisplay field value
func (o *ShippingMethod) GetDeliveryTimeRangeDisplay() DeliveryTimeRangeDisplay {
	if o == nil {
		var ret DeliveryTimeRangeDisplay
		return ret
	}

	return o.DeliveryTimeRangeDisplay
}

// GetDeliveryTimeRangeDisplayOk returns a tuple with the DeliveryTimeRangeDisplay field value
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetDeliveryTimeRangeDisplayOk() (*DeliveryTimeRangeDisplay, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeliveryTimeRangeDisplay, true
}

// SetDeliveryTimeRangeDisplay sets field value
func (o *ShippingMethod) SetDeliveryTimeRangeDisplay(v DeliveryTimeRangeDisplay) {
	o.DeliveryTimeRangeDisplay = v
}

// GetInventoryAddress returns the InventoryAddress field value
func (o *ShippingMethod) GetInventoryAddress() BusinessAddress {
	if o == nil {
		var ret BusinessAddress
		return ret
	}

	return o.InventoryAddress
}

// GetInventoryAddressOk returns a tuple with the InventoryAddress field value
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetInventoryAddressOk() (*BusinessAddress, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InventoryAddress, true
}

// SetInventoryAddress sets field value
func (o *ShippingMethod) SetInventoryAddress(v BusinessAddress) {
	o.InventoryAddress = v
}

// GetIsPayAtDestination returns the IsPayAtDestination field value if set, zero value otherwise.
func (o *ShippingMethod) GetIsPayAtDestination() bool {
	if o == nil || IsNil(o.IsPayAtDestination) {
		var ret bool
		return ret
	}
	return *o.IsPayAtDestination
}

// GetIsPayAtDestinationOk returns a tuple with the IsPayAtDestination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingMethod) GetIsPayAtDestinationOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPayAtDestination) {
		return nil, false
	}
	return o.IsPayAtDestination, true
}

// HasIsPayAtDestination returns a boolean if a field has been set.
func (o *ShippingMethod) HasIsPayAtDestination() bool {
	if o != nil && !IsNil(o.IsPayAtDestination) {
		return true
	}

	return false
}

// SetIsPayAtDestination gets a reference to the given bool and assigns it to the IsPayAtDestination field.
func (o *ShippingMethod) SetIsPayAtDestination(v bool) {
	o.IsPayAtDestination = &v
}

func (o ShippingMethod) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShippingMethod) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ShippingType) {
		toSerialize["shipping_type"] = o.ShippingType
	}
	toSerialize["get_shipping_type_display"] = o.GetShippingTypeDisplay
	toSerialize["shipping_type_display"] = o.ShippingTypeDisplay
	if !IsNil(o.Cost) {
		toSerialize["cost"] = o.Cost
	}
	if !IsNil(o.SecondaryCost) {
		toSerialize["secondary_cost"] = o.SecondaryCost
	}
	if !IsNil(o.MinimumTimeSending) {
		toSerialize["minimum_time_sending"] = o.MinimumTimeSending
	}
	if !IsNil(o.MaximumTimeSending) {
		toSerialize["maximum_time_sending"] = o.MaximumTimeSending
	}
	toSerialize["delivery_time_display"] = o.DeliveryTimeDisplay
	toSerialize["delivery_time_range_display"] = o.DeliveryTimeRangeDisplay
	toSerialize["inventory_address"] = o.InventoryAddress
	if !IsNil(o.IsPayAtDestination) {
		toSerialize["is_pay_at_destination"] = o.IsPayAtDestination
	}
	return toSerialize, nil
}

func (o *ShippingMethod) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"get_shipping_type_display",
		"shipping_type_display",
		"delivery_time_display",
		"delivery_time_range_display",
		"inventory_address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varShippingMethod := _ShippingMethod{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varShippingMethod)

	if err != nil {
		return err
	}

	*o = ShippingMethod(varShippingMethod)

	return err
}

type NullableShippingMethod struct {
	value *ShippingMethod
	isSet bool
}

func (v NullableShippingMethod) Get() *ShippingMethod {
	return v.value
}

func (v *NullableShippingMethod) Set(val *ShippingMethod) {
	v.value = val
	v.isSet = true
}

func (v NullableShippingMethod) IsSet() bool {
	return v.isSet
}

func (v *NullableShippingMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShippingMethod(val *ShippingMethod) *NullableShippingMethod {
	return &NullableShippingMethod{value: val, isSet: true}
}

func (v NullableShippingMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShippingMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


