/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MerchantOrderReviveShipmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MerchantOrderReviveShipmentResponse{}

// MerchantOrderReviveShipmentResponse struct for MerchantOrderReviveShipmentResponse
type MerchantOrderReviveShipmentResponse struct {
	// Success message
	Message string `json:"message"`
	// Order unique identifier
	OrderUuid string `json:"order_uuid"`
	// Current order status  * `1` - اولیه * `2` - شروع شده * `3` - در انتظار * `4` - در انتظار درگاه * `5` - منقضی شده * `6` - لغو شده * `7` - پرداخت‌شده توسط کاربر * `8` - پرداخت موفیت آمیز نبود * `9` - تأیید شده توسط فروشگاه * `10` - تأیید توسط فروشگاه ناموفق بود * `11` - ناموفق از سوی فروشگاه * `12` - لغوشده توسط فروشگاه * `13` - درخواست بازگشت وجه به مشتری به دلیل درخواست مشتری * `14` - درخواست بازگشت وجه به فروشگاه پس از عدم تأیید توسط فروشگاه * `15` - درخواست بازگشت وجه به مشتری پس از ناموفق بودن توسط فروشگاه * `16` - بازپرداخت به فروشگاه پس از لغو توسط فروشگاه * `17` - بازپرداخت تکمیل شد * `18` - زمان انقضا گذشته است * `19` - تحویل شده * `20` - جمع اوری شده و در حال ارسال
	Status OrderStatusEnum `json:"status"`
	// Human-readable status
	StatusDisplay string `json:"status_display"`
}

type _MerchantOrderReviveShipmentResponse MerchantOrderReviveShipmentResponse

// NewMerchantOrderReviveShipmentResponse instantiates a new MerchantOrderReviveShipmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMerchantOrderReviveShipmentResponse(message string, orderUuid string, status OrderStatusEnum, statusDisplay string) *MerchantOrderReviveShipmentResponse {
	this := MerchantOrderReviveShipmentResponse{}
	this.Message = message
	this.OrderUuid = orderUuid
	this.Status = status
	this.StatusDisplay = statusDisplay
	return &this
}

// NewMerchantOrderReviveShipmentResponseWithDefaults instantiates a new MerchantOrderReviveShipmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMerchantOrderReviveShipmentResponseWithDefaults() *MerchantOrderReviveShipmentResponse {
	this := MerchantOrderReviveShipmentResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *MerchantOrderReviveShipmentResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *MerchantOrderReviveShipmentResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *MerchantOrderReviveShipmentResponse) SetMessage(v string) {
	o.Message = v
}

// GetOrderUuid returns the OrderUuid field value
func (o *MerchantOrderReviveShipmentResponse) GetOrderUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderUuid
}

// GetOrderUuidOk returns a tuple with the OrderUuid field value
// and a boolean to check if the value has been set.
func (o *MerchantOrderReviveShipmentResponse) GetOrderUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderUuid, true
}

// SetOrderUuid sets field value
func (o *MerchantOrderReviveShipmentResponse) SetOrderUuid(v string) {
	o.OrderUuid = v
}

// GetStatus returns the Status field value
func (o *MerchantOrderReviveShipmentResponse) GetStatus() OrderStatusEnum {
	if o == nil {
		var ret OrderStatusEnum
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *MerchantOrderReviveShipmentResponse) GetStatusOk() (*OrderStatusEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *MerchantOrderReviveShipmentResponse) SetStatus(v OrderStatusEnum) {
	o.Status = v
}

// GetStatusDisplay returns the StatusDisplay field value
func (o *MerchantOrderReviveShipmentResponse) GetStatusDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StatusDisplay
}

// GetStatusDisplayOk returns a tuple with the StatusDisplay field value
// and a boolean to check if the value has been set.
func (o *MerchantOrderReviveShipmentResponse) GetStatusDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusDisplay, true
}

// SetStatusDisplay sets field value
func (o *MerchantOrderReviveShipmentResponse) SetStatusDisplay(v string) {
	o.StatusDisplay = v
}

func (o MerchantOrderReviveShipmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MerchantOrderReviveShipmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["order_uuid"] = o.OrderUuid
	toSerialize["status"] = o.Status
	toSerialize["status_display"] = o.StatusDisplay
	return toSerialize, nil
}

func (o *MerchantOrderReviveShipmentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"order_uuid",
		"status",
		"status_display",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMerchantOrderReviveShipmentResponse := _MerchantOrderReviveShipmentResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMerchantOrderReviveShipmentResponse)

	if err != nil {
		return err
	}

	*o = MerchantOrderReviveShipmentResponse(varMerchantOrderReviveShipmentResponse)

	return err
}

type NullableMerchantOrderReviveShipmentResponse struct {
	value *MerchantOrderReviveShipmentResponse
	isSet bool
}

func (v NullableMerchantOrderReviveShipmentResponse) Get() *MerchantOrderReviveShipmentResponse {
	return v.value
}

func (v *NullableMerchantOrderReviveShipmentResponse) Set(val *MerchantOrderReviveShipmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMerchantOrderReviveShipmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMerchantOrderReviveShipmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMerchantOrderReviveShipmentResponse(val *MerchantOrderReviveShipmentResponse) *NullableMerchantOrderReviveShipmentResponse {
	return &NullableMerchantOrderReviveShipmentResponse{value: val, isSet: true}
}

func (v NullableMerchantOrderReviveShipmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMerchantOrderReviveShipmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


