/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthStatusResponse{}

// AuthStatusResponse struct for AuthStatusResponse
type AuthStatusResponse struct {
	// Authentication status
	IsAuthenticated bool `json:"is_authenticated"`
}

type _AuthStatusResponse AuthStatusResponse

// NewAuthStatusResponse instantiates a new AuthStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthStatusResponse(isAuthenticated bool) *AuthStatusResponse {
	this := AuthStatusResponse{}
	this.IsAuthenticated = isAuthenticated
	return &this
}

// NewAuthStatusResponseWithDefaults instantiates a new AuthStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthStatusResponseWithDefaults() *AuthStatusResponse {
	this := AuthStatusResponse{}
	return &this
}

// GetIsAuthenticated returns the IsAuthenticated field value
func (o *AuthStatusResponse) GetIsAuthenticated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsAuthenticated
}

// GetIsAuthenticatedOk returns a tuple with the IsAuthenticated field value
// and a boolean to check if the value has been set.
func (o *AuthStatusResponse) GetIsAuthenticatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsAuthenticated, true
}

// SetIsAuthenticated sets field value
func (o *AuthStatusResponse) SetIsAuthenticated(v bool) {
	o.IsAuthenticated = v
}

func (o AuthStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["is_authenticated"] = o.IsAuthenticated
	return toSerialize, nil
}

func (o *AuthStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"is_authenticated",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthStatusResponse := _AuthStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthStatusResponse)

	if err != nil {
		return err
	}

	*o = AuthStatusResponse(varAuthStatusResponse)

	return err
}

type NullableAuthStatusResponse struct {
	value *AuthStatusResponse
	isSet bool
}

func (v NullableAuthStatusResponse) Get() *AuthStatusResponse {
	return v.value
}

func (v *NullableAuthStatusResponse) Set(val *AuthStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthStatusResponse(val *AuthStatusResponse) *NullableAuthStatusResponse {
	return &NullableAuthStatusResponse{value: val, isSet: true}
}

func (v NullableAuthStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


