/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Packing type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Packing{}

// Packing struct for Packing
type Packing struct {
	Id int32 `json:"id"`
	// نام روش/گزینه بسته‌بندی
	Name string `json:"name"`
	// هزینه بسته بندی به تومان
	Price *int32 `json:"price,omitempty"`
}

type _Packing Packing

// NewPacking instantiates a new Packing object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPacking(id int32, name string) *Packing {
	this := Packing{}
	this.Id = id
	this.Name = name
	return &this
}

// NewPackingWithDefaults instantiates a new Packing object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPackingWithDefaults() *Packing {
	this := Packing{}
	return &this
}

// GetId returns the Id field value
func (o *Packing) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Packing) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Packing) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Packing) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Packing) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Packing) SetName(v string) {
	o.Name = v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *Packing) GetPrice() int32 {
	if o == nil || IsNil(o.Price) {
		var ret int32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Packing) GetPriceOk() (*int32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *Packing) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given int32 and assigns it to the Price field.
func (o *Packing) SetPrice(v int32) {
	o.Price = &v
}

func (o Packing) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Packing) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	return toSerialize, nil
}

func (o *Packing) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPacking := _Packing{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPacking)

	if err != nil {
		return err
	}

	*o = Packing(varPacking)

	return err
}

type NullablePacking struct {
	value *Packing
	isSet bool
}

func (v NullablePacking) Get() *Packing {
	return v.value
}

func (v *NullablePacking) Set(val *Packing) {
	v.value = val
	v.isSet = true
}

func (v NullablePacking) IsSet() bool {
	return v.isSet
}

func (v *NullablePacking) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePacking(val *Packing) *NullablePacking {
	return &NullablePacking{value: val, isSet: true}
}

func (v NullablePacking) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePacking) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


