/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MerchantOrderRefundResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MerchantOrderRefundResponse{}

// MerchantOrderRefundResponse struct for MerchantOrderRefundResponse
type MerchantOrderRefundResponse struct {
	Message string `json:"message"`
	OrderUuid string `json:"order_uuid"`
	Status OrderStatusEnum `json:"status"`
	StatusDisplay string `json:"status_display"`
	RefundReason string `json:"refund_reason"`
}

type _MerchantOrderRefundResponse MerchantOrderRefundResponse

// NewMerchantOrderRefundResponse instantiates a new MerchantOrderRefundResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMerchantOrderRefundResponse(message string, orderUuid string, status OrderStatusEnum, statusDisplay string, refundReason string) *MerchantOrderRefundResponse {
	this := MerchantOrderRefundResponse{}
	this.Message = message
	this.OrderUuid = orderUuid
	this.Status = status
	this.StatusDisplay = statusDisplay
	this.RefundReason = refundReason
	return &this
}

// NewMerchantOrderRefundResponseWithDefaults instantiates a new MerchantOrderRefundResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMerchantOrderRefundResponseWithDefaults() *MerchantOrderRefundResponse {
	this := MerchantOrderRefundResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *MerchantOrderRefundResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *MerchantOrderRefundResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *MerchantOrderRefundResponse) SetMessage(v string) {
	o.Message = v
}

// GetOrderUuid returns the OrderUuid field value
func (o *MerchantOrderRefundResponse) GetOrderUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderUuid
}

// GetOrderUuidOk returns a tuple with the OrderUuid field value
// and a boolean to check if the value has been set.
func (o *MerchantOrderRefundResponse) GetOrderUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderUuid, true
}

// SetOrderUuid sets field value
func (o *MerchantOrderRefundResponse) SetOrderUuid(v string) {
	o.OrderUuid = v
}

// GetStatus returns the Status field value
func (o *MerchantOrderRefundResponse) GetStatus() OrderStatusEnum {
	if o == nil {
		var ret OrderStatusEnum
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *MerchantOrderRefundResponse) GetStatusOk() (*OrderStatusEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *MerchantOrderRefundResponse) SetStatus(v OrderStatusEnum) {
	o.Status = v
}

// GetStatusDisplay returns the StatusDisplay field value
func (o *MerchantOrderRefundResponse) GetStatusDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StatusDisplay
}

// GetStatusDisplayOk returns a tuple with the StatusDisplay field value
// and a boolean to check if the value has been set.
func (o *MerchantOrderRefundResponse) GetStatusDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusDisplay, true
}

// SetStatusDisplay sets field value
func (o *MerchantOrderRefundResponse) SetStatusDisplay(v string) {
	o.StatusDisplay = v
}

// GetRefundReason returns the RefundReason field value
func (o *MerchantOrderRefundResponse) GetRefundReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefundReason
}

// GetRefundReasonOk returns a tuple with the RefundReason field value
// and a boolean to check if the value has been set.
func (o *MerchantOrderRefundResponse) GetRefundReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefundReason, true
}

// SetRefundReason sets field value
func (o *MerchantOrderRefundResponse) SetRefundReason(v string) {
	o.RefundReason = v
}

func (o MerchantOrderRefundResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MerchantOrderRefundResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["order_uuid"] = o.OrderUuid
	toSerialize["status"] = o.Status
	toSerialize["status_display"] = o.StatusDisplay
	toSerialize["refund_reason"] = o.RefundReason
	return toSerialize, nil
}

func (o *MerchantOrderRefundResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"order_uuid",
		"status",
		"status_display",
		"refund_reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMerchantOrderRefundResponse := _MerchantOrderRefundResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMerchantOrderRefundResponse)

	if err != nil {
		return err
	}

	*o = MerchantOrderRefundResponse(varMerchantOrderRefundResponse)

	return err
}

type NullableMerchantOrderRefundResponse struct {
	value *MerchantOrderRefundResponse
	isSet bool
}

func (v NullableMerchantOrderRefundResponse) Get() *MerchantOrderRefundResponse {
	return v.value
}

func (v *NullableMerchantOrderRefundResponse) Set(val *MerchantOrderRefundResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMerchantOrderRefundResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMerchantOrderRefundResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMerchantOrderRefundResponse(val *MerchantOrderRefundResponse) *NullableMerchantOrderRefundResponse {
	return &NullableMerchantOrderRefundResponse{value: val, isSet: true}
}

func (v NullableMerchantOrderRefundResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMerchantOrderRefundResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


