/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"fmt"
)

// OrderStatusEnum * `1` - اولیه * `2` - شروع شده * `3` - در انتظار * `4` - در انتظار درگاه * `5` - منقضی شده * `6` - لغو شده * `7` - پرداخت‌شده توسط کاربر * `8` - پرداخت موفیت آمیز نبود * `9` - تأیید شده توسط فروشگاه * `10` - تأیید توسط فروشگاه ناموفق بود * `11` - ناموفق از سوی فروشگاه * `12` - لغوشده توسط فروشگاه * `13` - درخواست بازگشت وجه به مشتری به دلیل درخواست مشتری * `14` - درخواست بازگشت وجه به فروشگاه پس از عدم تأیید توسط فروشگاه * `15` - درخواست بازگشت وجه به مشتری پس از ناموفق بودن توسط فروشگاه * `16` - بازپرداخت به فروشگاه پس از لغو توسط فروشگاه * `17` - بازپرداخت تکمیل شد * `18` - زمان انقضا گذشته است * `19` - تحویل شده * `20` - جمع اوری شده و در حال ارسال
type OrderStatusEnum int32

// List of OrderStatusEnum
const (
	_1 OrderStatusEnum = 1
	_2 OrderStatusEnum = 2
	_3 OrderStatusEnum = 3
	_4 OrderStatusEnum = 4
	_5 OrderStatusEnum = 5
	_6 OrderStatusEnum = 6
	_7 OrderStatusEnum = 7
	_8 OrderStatusEnum = 8
	_9 OrderStatusEnum = 9
	_10 OrderStatusEnum = 10
	_11 OrderStatusEnum = 11
	_12 OrderStatusEnum = 12
	_13 OrderStatusEnum = 13
	_14 OrderStatusEnum = 14
	_15 OrderStatusEnum = 15
	_16 OrderStatusEnum = 16
	_17 OrderStatusEnum = 17
	_18 OrderStatusEnum = 18
	_19 OrderStatusEnum = 19
	_20 OrderStatusEnum = 20
)

// All allowed values of OrderStatusEnum enum
var AllowedOrderStatusEnumEnumValues = []OrderStatusEnum{
	1,
	2,
	3,
	4,
	5,
	6,
	7,
	8,
	9,
	10,
	11,
	12,
	13,
	14,
	15,
	16,
	17,
	18,
	19,
	20,
}

func (v *OrderStatusEnum) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OrderStatusEnum(value)
	for _, existing := range AllowedOrderStatusEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OrderStatusEnum", value)
}

// NewOrderStatusEnumFromValue returns a pointer to a valid OrderStatusEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOrderStatusEnumFromValue(v int32) (*OrderStatusEnum, error) {
	ev := OrderStatusEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OrderStatusEnum: valid values are %v", v, AllowedOrderStatusEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OrderStatusEnum) IsValid() bool {
	for _, existing := range AllowedOrderStatusEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OrderStatusEnum value
func (v OrderStatusEnum) Ptr() *OrderStatusEnum {
	return &v
}

type NullableOrderStatusEnum struct {
	value *OrderStatusEnum
	isSet bool
}

func (v NullableOrderStatusEnum) Get() *OrderStatusEnum {
	return v.value
}

func (v *NullableOrderStatusEnum) Set(val *OrderStatusEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderStatusEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderStatusEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderStatusEnum(val *OrderStatusEnum) *NullableOrderStatusEnum {
	return &NullableOrderStatusEnum{value: val, isSet: true}
}

func (v NullableOrderStatusEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderStatusEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

