/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrderCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCreateResponse{}

// OrderCreateResponse struct for OrderCreateResponse
type OrderCreateResponse struct {
	OrderStartUrl string `json:"order_start_url"`
	OrderUuid string `json:"order_uuid"`
}

type _OrderCreateResponse OrderCreateResponse

// NewOrderCreateResponse instantiates a new OrderCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCreateResponse(orderStartUrl string, orderUuid string) *OrderCreateResponse {
	this := OrderCreateResponse{}
	this.OrderStartUrl = orderStartUrl
	this.OrderUuid = orderUuid
	return &this
}

// NewOrderCreateResponseWithDefaults instantiates a new OrderCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCreateResponseWithDefaults() *OrderCreateResponse {
	this := OrderCreateResponse{}
	return &this
}

// GetOrderStartUrl returns the OrderStartUrl field value
func (o *OrderCreateResponse) GetOrderStartUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderStartUrl
}

// GetOrderStartUrlOk returns a tuple with the OrderStartUrl field value
// and a boolean to check if the value has been set.
func (o *OrderCreateResponse) GetOrderStartUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderStartUrl, true
}

// SetOrderStartUrl sets field value
func (o *OrderCreateResponse) SetOrderStartUrl(v string) {
	o.OrderStartUrl = v
}

// GetOrderUuid returns the OrderUuid field value
func (o *OrderCreateResponse) GetOrderUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderUuid
}

// GetOrderUuidOk returns a tuple with the OrderUuid field value
// and a boolean to check if the value has been set.
func (o *OrderCreateResponse) GetOrderUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderUuid, true
}

// SetOrderUuid sets field value
func (o *OrderCreateResponse) SetOrderUuid(v string) {
	o.OrderUuid = v
}

func (o OrderCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["order_start_url"] = o.OrderStartUrl
	toSerialize["order_uuid"] = o.OrderUuid
	return toSerialize, nil
}

func (o *OrderCreateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"order_start_url",
		"order_uuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderCreateResponse := _OrderCreateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrderCreateResponse)

	if err != nil {
		return err
	}

	*o = OrderCreateResponse(varOrderCreateResponse)

	return err
}

type NullableOrderCreateResponse struct {
	value *OrderCreateResponse
	isSet bool
}

func (v NullableOrderCreateResponse) Get() *OrderCreateResponse {
	return v.value
}

func (v *NullableOrderCreateResponse) Set(val *OrderCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCreateResponse(val *OrderCreateResponse) *NullableOrderCreateResponse {
	return &NullableOrderCreateResponse{value: val, isSet: true}
}

func (v NullableOrderCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


