/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Option type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Option{}

// Option struct for Option
type Option struct {
	// نوع ویژگی محصول: رنگ، سایز، گارانتی، وزن یا سایر  * `color` - رنگ * `size` - اندازه * `warranty` - گارانتی * `weight` - وزن * `other` - سایر
	TypeName TypeNameEnum `json:"type_name"`
	// نام ویژگی (مثلاً 'قرمز' برای رنگ قرمز، 'XL' برای سایز)
	Name string `json:"name"`
	// مقدار ویژگی (مثلاً '#FF0000' برای کد رنگ یا مقدار دیگر)
	Value string `json:"value"`
	// اگر نوع ویژگی رنگ است درست است، وگرنه غلط
	IsColor *bool `json:"is_color,omitempty"`
}

type _Option Option

// NewOption instantiates a new Option object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOption(typeName TypeNameEnum, name string, value string) *Option {
	this := Option{}
	this.TypeName = typeName
	this.Name = name
	this.Value = value
	var isColor bool = false
	this.IsColor = &isColor
	return &this
}

// NewOptionWithDefaults instantiates a new Option object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOptionWithDefaults() *Option {
	this := Option{}
	var isColor bool = false
	this.IsColor = &isColor
	return &this
}

// GetTypeName returns the TypeName field value
func (o *Option) GetTypeName() TypeNameEnum {
	if o == nil {
		var ret TypeNameEnum
		return ret
	}

	return o.TypeName
}

// GetTypeNameOk returns a tuple with the TypeName field value
// and a boolean to check if the value has been set.
func (o *Option) GetTypeNameOk() (*TypeNameEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TypeName, true
}

// SetTypeName sets field value
func (o *Option) SetTypeName(v TypeNameEnum) {
	o.TypeName = v
}

// GetName returns the Name field value
func (o *Option) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Option) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Option) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *Option) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *Option) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *Option) SetValue(v string) {
	o.Value = v
}

// GetIsColor returns the IsColor field value if set, zero value otherwise.
func (o *Option) GetIsColor() bool {
	if o == nil || IsNil(o.IsColor) {
		var ret bool
		return ret
	}
	return *o.IsColor
}

// GetIsColorOk returns a tuple with the IsColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Option) GetIsColorOk() (*bool, bool) {
	if o == nil || IsNil(o.IsColor) {
		return nil, false
	}
	return o.IsColor, true
}

// HasIsColor returns a boolean if a field has been set.
func (o *Option) HasIsColor() bool {
	if o != nil && !IsNil(o.IsColor) {
		return true
	}

	return false
}

// SetIsColor gets a reference to the given bool and assigns it to the IsColor field.
func (o *Option) SetIsColor(v bool) {
	o.IsColor = &v
}

func (o Option) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Option) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type_name"] = o.TypeName
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value
	if !IsNil(o.IsColor) {
		toSerialize["is_color"] = o.IsColor
	}
	return toSerialize, nil
}

func (o *Option) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type_name",
		"name",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOption := _Option{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOption)

	if err != nil {
		return err
	}

	*o = Option(varOption)

	return err
}

type NullableOption struct {
	value *Option
	isSet bool
}

func (v NullableOption) Get() *Option {
	return v.value
}

func (v *NullableOption) Set(val *Option) {
	v.value = val
	v.isSet = true
}

func (v NullableOption) IsSet() bool {
	return v.isSet
}

func (v *NullableOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOption(val *Option) *NullableOption {
	return &NullableOption{value: val, isSet: true}
}

func (v NullableOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


