/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrderError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderError{}

// OrderError struct for OrderError
type OrderError struct {
	Error ErrorEnum `json:"error"`
}

type _OrderError OrderError

// NewOrderError instantiates a new OrderError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderError(error_ ErrorEnum) *OrderError {
	this := OrderError{}
	this.Error = error_
	return &this
}

// NewOrderErrorWithDefaults instantiates a new OrderError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderErrorWithDefaults() *OrderError {
	this := OrderError{}
	return &this
}

// GetError returns the Error field value
func (o *OrderError) GetError() ErrorEnum {
	if o == nil {
		var ret ErrorEnum
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *OrderError) GetErrorOk() (*ErrorEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *OrderError) SetError(v ErrorEnum) {
	o.Error = v
}

func (o OrderError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *OrderError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderError := _OrderError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrderError)

	if err != nil {
		return err
	}

	*o = OrderError(varOrderError)

	return err
}

type NullableOrderError struct {
	value *OrderError
	isSet bool
}

func (v NullableOrderError) Get() *OrderError {
	return v.value
}

func (v *NullableOrderError) Set(val *OrderError) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderError) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderError(val *OrderError) *NullableOrderError {
	return &NullableOrderError{value: val, isSet: true}
}

func (v NullableOrderError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


