/*
BWDK API

<div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bwdk_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerifyOrder type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyOrder{}

// VerifyOrder struct for VerifyOrder
type VerifyOrder struct {
	// شناسه منحصر به فرد ارسال شده هنگام ساخت سفارش برای تأیید اصالت سفارش
	MerchantUniqueId string `json:"merchant_unique_id"`
}

type _VerifyOrder VerifyOrder

// NewVerifyOrder instantiates a new VerifyOrder object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyOrder(merchantUniqueId string) *VerifyOrder {
	this := VerifyOrder{}
	this.MerchantUniqueId = merchantUniqueId
	return &this
}

// NewVerifyOrderWithDefaults instantiates a new VerifyOrder object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyOrderWithDefaults() *VerifyOrder {
	this := VerifyOrder{}
	return &this
}

// GetMerchantUniqueId returns the MerchantUniqueId field value
func (o *VerifyOrder) GetMerchantUniqueId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MerchantUniqueId
}

// GetMerchantUniqueIdOk returns a tuple with the MerchantUniqueId field value
// and a boolean to check if the value has been set.
func (o *VerifyOrder) GetMerchantUniqueIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MerchantUniqueId, true
}

// SetMerchantUniqueId sets field value
func (o *VerifyOrder) SetMerchantUniqueId(v string) {
	o.MerchantUniqueId = v
}

func (o VerifyOrder) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyOrder) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["merchant_unique_id"] = o.MerchantUniqueId
	return toSerialize, nil
}

func (o *VerifyOrder) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"merchant_unique_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifyOrder := _VerifyOrder{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerifyOrder)

	if err != nil {
		return err
	}

	*o = VerifyOrder(varVerifyOrder)

	return err
}

type NullableVerifyOrder struct {
	value *VerifyOrder
	isSet bool
}

func (v NullableVerifyOrder) Get() *VerifyOrder {
	return v.value
}

func (v *NullableVerifyOrder) Set(val *VerifyOrder) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyOrder) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyOrder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyOrder(val *VerifyOrder) *NullableVerifyOrder {
	return &NullableVerifyOrder{value: val, isSet: true}
}

func (v NullableVerifyOrder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyOrder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


